artexhibit/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")), 
    path("user/", include("userauths.urls")),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("paypal/",include("paypal.standard.ipn.urls")),
    
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path,include
from core.views import index, product_list_view, category_list_view,category_product_list_view,artist_list_view,artist_detail_view,product_detail_view,tag_list,ajax_add_review,search_view,filter_product,add_to_cart,cart_view,delete_item_from_cart,update_cart,checkout,payment_completed_view,payment_failed_view,customer_dashboard,order_detail,make_address_default,wishlist_view,add_to_wishlist,remove_wishlist,save_checkout_info




app_name = "core"

urlpatterns = [
    #Home
    path("", index, name="index"),
    path("products/", product_list_view, name= "product-list"),
    path("product/<pid>/", product_detail_view, name= "product-detail"),

    #Category
    path("category/", category_list_view, name= "category-list"),
    path("category/<cid>/", category_product_list_view, name= "category-product-list"),

    #Artist
    path("artists/", artist_list_view, name= "artist-list"),
    path("artist/<aid>", artist_detail_view, name= "artist-detail"),

    #Tags
    path("products/tag/<tag_slug>/", tag_list, name="tags"),

    #Reviews
    path("ajax-add-review/<pid>/",ajax_add_review,name ="ajax-add-review"),

    #Search
    path("search/",search_view,name="search"),

    #Filter
    path("filter-products/",filter_product,name="filter-product"),

    #addtocart
    path("add-to-cart/",add_to_cart,name="add-to-cart"),

    #Cart page 
    path("cart/",cart_view,name="cart"),


    #Delete Item from cart
    path("delete-from-cart/",delete_item_from_cart,name="delete-from-cart"),

    #Update Item from cart
    path("update-cart/",update_cart,name="update-cart"),

    #Checkout
    path("checkout/<oid>/",checkout,name="checkout"),

    #Paypal 
    path("paypal/",include("paypal.standard.ipn.urls")),

    #Payment Successful
    path("payment-completed/<oid>/",payment_completed_view,name="payment-completed"),

    #Payment Failed
    path("payment-failed/",payment_failed_view,name="payment-failed"),

    #dashboard
    path("dashboard/",customer_dashboard,name="dashboard"),

    #OrderDetail Url
    path("dashboard/order/<int:id>",order_detail,name="order-detail"),

    #make address default
    path("make-default-address/",make_address_default,name="make-default-address"),

    #wishlist page
    path("wishlist/",wishlist_view,name="wishlist"),

    #add to wishlist
    path("add-to-wishlist/",add_to_wishlist,name="add-to-wishlist"),

    #removing from wishlist
    path("remove-from-wishlist/",remove_wishlist,name="remove-from-wishlist"),

    

    path("save_checkout_info/",save_checkout_info, name="save_checkout_info")

]

core/forms.py
from django import forms
from core.models import ProductReview

class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs= {"placeholder": "Write Review"}))

    class Meta:
        model = ProductReview
        fields = ['review','rating']

core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,get_object_or_404,redirect
from django.db.models import Count,Avg
from taggit.models import Tag
from core.models import Product, Category, Artist, CartOrder, CartOrderItems, ProductImages,ProductReview,Address,wishlist_model,Coupon
from core.forms import ProductReviewForm
from django.template.loader import render_to_string
from django.contrib import messages

from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from paypal.standard.forms import PayPalPaymentsForm
from django.core import serializers
from userauths.models import Profile

import calendar
from django.db.models.functions import ExtractMonth

def index(request):
    products = Product.objects.filter(featured=True, products_status="published")
    context = {
        "products":products
    }

    return render(request,'core/index.html',context)

def product_list_view(request):
    products = Product.objects.filter(products_status="published")
    

    context = {
        "products":products,
       
    }
    return render(request,'core/product-list.html',context)

def category_list_view(request):

    categories = Category.objects.all()
    context = {
        "categories":categories
    }
    return render(request,'core/category-list.html',context)

def category_product_list_view(request,cid):
    category = Category.objects.get(cid = cid)
    products = Product.objects.filter(products_status="published", category=category)

    context = {
        "category":category,
        "products":products,
    }
    return render(request, "core/category-product-list.html",context)

def artist_list_view(request):
    artists = Artist.objects.all()
    context = {
        "artist": artists,
    }
    return render(request, "core/artist-list.html",context)

def artist_detail_view(request,aid):
    artist = Artist.objects.get(aid = aid)
    products = Product.objects.filter(artist=artist, products_status="published")
    context = {
        "artist": artist,
        "products": products,
    }
    return render(request, "core/artist-detail.html",context)  



@login_required

def product_detail_view(request,pid):
    product = Product.objects.get(pid=pid) 

    products= Product.objects.filter(category=product.category).exclude(pid=pid)

   

    address = Address.objects.filter(user=request.user)

    #getting all review
    reviews = ProductReview.objects.filter(product=product).order_by("-date")

    #getting average review
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    #product Review Form
    review_form = ProductReviewForm()

    make_review = True

    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    p_image = product.p_images.all() 
    context = {
        "p": product,
        "p_image": p_image,
        "average_rating": average_rating,
        "reviews": reviews,
        "make_review": make_review,
        "review_form":review_form,
        "products": products,
        "address":address,
      
    }    
    return render(request,"core/product-detail.html",context)

def tag_list(request,tag_slug=None):
    products = Product.objects.filter(products_status="published").order_by("-id")

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context={
        "products": products,
        "tag":tag,
    }    
    return render(request, "core/tag.html",context)

def ajax_add_review(request,pid):
    product = Product.objects.get(pid=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST['review'],
        rating=request.POST['rating'],
    )

    context = {
        'user':user.username,
        'review':request.POST['review'],
        'rating':request.POST['rating'],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
        {
        'bool': True,
        'context': context,
        'average_reviews': average_reviews

        }
        
    )

def search_view(request):
    query = request.GET.get("q")


    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products":products,
        "query":query,

    }    
    return render(request, "core/search.html",context)


def filter_product(request):
    categories = request.GET.getlist('category[]')
    artists = request.GET.getlist('artist[]')
    tags = request.GET.getlist('tag[]')


    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(products_status="published").order_by("-id").distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(artists) > 0:
        products = products.filter(artist__id__in=artists).distinct()  

    if tags:
        products = products.filter(tags__id__in=tags).distinct()

   

    data = render_to_string("core/async/product-list.html",{"products":products})
    return JsonResponse({"data":data})



def add_to_cart(request):
    cart_product = {}
    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'qty': int(request.GET['qty']),  
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],

    }

    if 'cart_data_obj' in request.session:
        cart_data = request.session['cart_data_obj']
        if str(request.GET['id']) in cart_data:
            
            cart_data[str(request.GET['id'])]['qty'] = int(request.GET['qty'])
        else:
            
            cart_data.update(cart_product)
    else:
        
        cart_data = cart_product

    
    request.session['cart_data_obj'] = cart_data

   
    return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})

@login_required         
def cart_view(request):
    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])
        return render(request, "core/cart.html",{"cart_data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})
    else:
        messages.warning(request, "Your cart is empty")
        return redirect("core:index") 



def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data 

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])    
    
    
    context = render_to_string("core/async/cart-list.html",{"cart_data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})

    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})

def update_cart(request):
    product_id = str(request.GET['id'])
    product_qty = request.GET['qty']

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['qty'] = product_qty
            request.session['cart_data_obj'] = cart_data 

    cart_total_amount = 0
    if 'cart_data_obj' in request.session:
        for p_id, item in request.session['cart_data_obj'].items():
            cart_total_amount += int(item['qty']) * float(item['price'])    
    
    
    context = render_to_string("core/async/cart-list.html",{"cart_data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total_amount':cart_total_amount})

    return JsonResponse({"data": context, 'totalcartitems': len(request.session['cart_data_obj'])})



def save_checkout_info(request):
    cart_total_amount = 0
    total_amount = 0

    if request.method == "POST":
        full_name = request.POST.get("full_name")
        email = request.POST.get("email")
        mobile = request.POST.get("mobile")
        address = request.POST.get("address")
        city = request.POST.get("city")
        state = request.POST.get("state")
        country = request.POST.get("country")

        request.session['full_name'] = full_name
        request.session['email'] = email
        request.session['mobile'] = mobile
        request.session['address'] = address
        request.session['city'] = city
        request.session['state'] = state
        request.session['country'] = country

        if 'cart_data_obj' in request.session:
            # Calculate total amount for PayPal payment
            for p_id, item in request.session['cart_data_obj'].items():
                total_amount += int(item['qty']) * float(item['price'])

            # Create Order Object
            order = CartOrder.objects.create(
                user=request.user,
                price=total_amount,
                full_name=full_name,
                email=email,

templates/core/artist-detail.html
{% extends 'partials/base.html' %}

{% load static%}
{%block content%}
    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Store <span></span>{{artist.title}}
                </div>
            </div>
        </div>
        <div class="container mb-30">
            <div class="archive-header-3 mt-30 mb-80" style="background-image: url({{artist.cover_image.url}})">
                <div class="archive-header-3-inner">
                    <div class="vendor-logo mr-50">
                        <img src="{{artist.image.url}}" alt="" />
                    </div>
                    <div class="vendor-content">
                        <div class="product-category">
                            <span class="text-muted">Since {{artist.date|date:"Y"}}</span>
                        </div>
                        <h3 class="mb-5 text-white"><a href="vendor-details-1.html" class="text-white">{{artist.title}}</a></h3>
                        <div class="product-rate-cover mb-15">
                          
                        </div>
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="vendor-des mb-15">
                                    <p class="font-sm text-white">{{artist.description|safe}}</p>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="vendor-info text-white mb-15">
                                    <ul class="font-sm">
                                        <li><img class="mr-5" src="{% static 'assets/imgs/theme/icons/icon-location.svg' %}" alt="" /><strong>Address: </strong> <span>{{artist.address}}</span></li>
                                        <li><img class="mr-5" src="{% static 'assets/imgs/theme/icons/icon-contact.svg' %}" alt="" /><strong>Call Us:</strong><span>{{artist.contact}}</span></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="follow-social">
                                    <h6 class="mb-15 text-white">Follow Us</h6>
                                    <ul class="social-network">
                                        <li class="hover-up">
                                            <a href="#">
                                                <img src="{% static 'assets/imgs/theme/icons/social-tw.svg' %}" alt="" />
                                            </a>
                                        </li>
                                        <li class="hover-up">
                                            <a href="#">
                                                <img src="{% static 'assets/imgs/theme/icons/social-fb.svg' %}" alt="" />
                                            </a>
                                        </li>
                                        <li class="hover-up">
                                            <a href="#">
                                                <img src="{% static 'assets/imgs/theme/icons/social-insta.svg' %}" alt="" />
                                            </a>
                                        </li>
                                        <li class="hover-up">
                                            <a href="#">
                                                <img src="{% static 'assets/imgs/theme/icons/social-pin.svg' %}" alt="" />
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row flex-row-reverse">
                <div class="col-lg-4-5">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p>We found <strong class="text-brand">{{products.count}}</strong> items for you!</p>
                        </div>
                        
                    </div>
                    <div class="product-list mb-50">
                        {% for p in products %}
                        <div class="product-cart-wrap">
                            <div class="product-img-action-wrap">
                                <div class="product-img product-img-zoom">
                                    <div class="product-img-inner">
                                        <a href="{% url 'core:product-detail' p.pid%}">
                                            <img class="default-img" src="{{p.image.url}}" alt="" />
                                            <img class="hover-img" src="{{p.image.url}}" alt="" />
                                        </a>
                                    </div>
                                </div>
                             
                                
                            </div>
                            <div class="product-content-wrap">
                                <div class="product-category">
                                    <a href="shop-grid-right.html">{{p.category.title}}</a>
                                </div>
                                <h2><a href="{% url 'core:product-detail' p.pid%}">{{p.title|truncatechars:50}}</a></h2>
                                <div class="product-description">
                                    <span class="ml-30">{{ p.description|safe }}</span>
                                </div>
                                <p class="mt-15 mb-15">{{ p.specifications|safe }}</p>
                                <div class="product-price">
                                    <span>${{ p.price }} </span>
                                    
                                </div>
                                
                          
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    

                </div>
                <div class="col-lg-1-5 primary-sidebar sticky-sidebar pt-30">
                    <div class="sidebar-widget widget-category-2 mb-30">
                        <h5 class="section-title style-1 mb-30">Category</h5>
                        <ul>
                            {% for c in categories %}
                            
                            <li>
                                <a href="{% url 'core:category-product-list' c.cid %}"> <img
                                        src="{{c.image.url}}"
                                        alt="" />{{c.title}}</a><span class="count">{{c.category.all.count}}</span>
                            </li>
                            {% endfor %}
                           
                        </ul>
                    </div>
    
    
    
                </div>
            </div>
        </div>
    </main>
  
    {%endblock content%}

templates/core/cart.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <main class="main" id="cart-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="/" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Cart
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Your Cart</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> products in your cart</h6>
                    </div>
                </div>
            </div>
            <form action="{% url 'core:save_checkout_info' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <div class="col-lg-8">
                        <div class="table-responsive shopping-summery">
                            <table class="table table-wishlist">
                                <thead>
                                    <tr class="main-heading">
                                        
                                        <th scope="col">Product</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Unit Price</th>
                                        <th scope="col" class="text-center">Quantity</th>
                                        <th scope="col">Subtotal</th>
                                        <th scope="col" class="">Refresh</th>
                                        <th scope="col" class="end">Remove</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product_id, item in cart_data.items %}
                                    <tr class="pt-30">
                                        <td class="image product-thumbnail pt-40"><img src="{{ item.image }}" alt="#"></td>
                                        <td class="product-des product-name">
                                            <h6 class="mb-5"><a class="product-name mb-10 text-heading" href="{% url 'core:product-detail' item.pid %}">{{ item.title }}</a></h6>
                                        
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-body">${{item.price|floatformat:2}}</h4>
                                        </td>
                                        <td class="text-center detail-info" data-title="Stock">
                                            <div class="mr-15">
                                                <input type="number" placeholder="Qty" class="w-25 product-qty-{{ product_id }}"  name="" value="{{ item.qty }}" id="">
                                            </div>
                                        </td>
                                        <td class="price" data-title="Price">
                                            <h4 class="text-brand">${% widthratio item.price 1 item.qty %} </h4>
                                        </td>
                                        <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body update-product" data-product="{{ product_id }}"><i class="fi-rs-refresh"></i></a></td>
                                        <td class="action text-center" data-title="Remove"><a style="border: none; background: none;"  class="text-body delete-product" data-product="{{ product_id }}"><i class="fi-rs-trash"></i></a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>

                            <div class="row mt-4">
                                <h4 class="mb-30">Bio Data</h4>
                                <div class="row">
                                    <div class="form-group col-lg-12">
                                        <label for="">Full Name</label>
                                        <input type="text" required="" name="full_name" value="{{request.user.username|title}}" placeholder="Full Name">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Email</label>
                                        <input type="text" required="" name="email"  placeholder="email*" value="{{request.user.email}}">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Mobile</label>
                                        <input type="text" name="mobile" value="{{request.user.profile.phone}}" required="" placeholder="Mobile *">
                                    </div>
                                </div>
                                <h4 class="mb-30">Shipping Details</h4>
                                <div class="row">
                                    <div class="form-group col-lg-6">
                                        <label for="">Address</label>
                                        <input type="text" name="address" value="" placeholder="Address">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">City</label>
                                        <input type="text" name="city"  placeholder="City *" value="">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">State</label>
                                        <input type="text" name="state" value="" placeholder="State *">
                                    </div>
                                    <div class="form-group col-lg-6">
                                        <label for="">Country</label>
                                        <input type="text" name="country" value="" placeholder="Country *">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="border p-md-4 cart-totals ml-30">
                            <div class="table-responsive">
                                <div>
                                    <!-- <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Tax</p>
                                        <p>$0</p>
                                    </div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Shipping</p>
                                        <p>$0</p>
                                    </div>
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Discount</p>
                                        <p>$0</p>
                                    </div> -->
                                    
                                    <div class="d-flex justify-content-between mb-2">
                                        <p class="fw-bold">Total</p>
                                        <p>${{cart_total_amount|floatformat:2}}</p>
                                    </div>
                                </div>
                            </div>
                            {% if totalcartitems %}
                                <button type="submit" class="btn mb-20 w-100">Proceed To CheckOut<i class="fi-rs-sign-out ml-15"></i></button>
                            {% endif %}                    
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </main>
{% endblock content %}