artexhibit/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")), 
    path("user/", include("userauths.urls")),
    path("ckeditor/",include("ckeditor_uploader.urls")),
    path("paypal/",include("paypal.standard.ipn.urls")),
    
    
]

if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

core/urls.py
from django.urls import path,include
from core.views import index, product_list_view, category_list_view,category_product_list_view,artist_list_view,artist_detail_view,product_detail_view,tag_list,ajax_add_review,search_view,filter_product,add_to_cart,cart_view,delete_item_from_cart,update_cart,checkout,payment_completed_view,payment_failed_view,customer_dashboard,order_detail,make_address_default,wishlist_view,add_to_wishlist,remove_wishlist,save_checkout_info




app_name = "core"

urlpatterns = [
    #Home
    path("", index, name="index"),
    path("products/", product_list_view, name= "product-list"),
    path("product/<pid>/", product_detail_view, name= "product-detail"),

    #Category
    path("category/", category_list_view, name= "category-list"),
    path("category/<cid>/", category_product_list_view, name= "category-product-list"),

    #Artist
    path("artists/", artist_list_view, name= "artist-list"),
    path("artist/<aid>", artist_detail_view, name= "artist-detail"),

    #Tags
    path("products/tag/<tag_slug>/", tag_list, name="tags"),

    #Reviews
    path("ajax-add-review/<pid>/",ajax_add_review,name ="ajax-add-review"),

    #Search
    path("search/",search_view,name="search"),

    #Filter
    path("filter-products/",filter_product,name="filter-product"),

    #addtocart
    path("add-to-cart/",add_to_cart,name="add-to-cart"),

    #Cart page 
    path("cart/",cart_view,name="cart"),


    #Delete Item from cart
    path("delete-from-cart/",delete_item_from_cart,name="delete-from-cart"),

    #Update Item from cart
    path("update-cart/",update_cart,name="update-cart"),

    #Checkout
    path("checkout/<oid>/",checkout,name="checkout"),

    #Paypal 
    path("paypal/",include("paypal.standard.ipn.urls")),

    #Payment Successful
    path("payment-completed/<oid>/",payment_completed_view,name="payment-completed"),

    #Payment Failed
    path("payment-failed/",payment_failed_view,name="payment-failed"),

    #dashboard
    path("dashboard/",customer_dashboard,name="dashboard"),

    #OrderDetail Url
    path("dashboard/order/<int:id>",order_detail,name="order-detail"),

    #make address default
    path("make-default-address/",make_address_default,name="make-default-address"),

    #wishlist page
    path("wishlist/",wishlist_view,name="wishlist"),

    #add to wishlist
    path("add-to-wishlist/",add_to_wishlist,name="add-to-wishlist"),

    #removing from wishlist
    path("remove-from-wishlist/",remove_wishlist,name="remove-from-wishlist"),

    

    path("save_checkout_info/",save_checkout_info, name="save_checkout_info")

]

userauths/urls.py
from django.urls import path
from userauths import views
from userauths.views import profile_update


app_name = "userauths"

urlpatterns= [
    path("sign-up/", views.register_view, name = "sign-up"),
    path("sign-in/", views.login_view, name = "sign-in"),
    path("sign-out/", views.logout_view, name = "sign-out"),
    path("profile/update/", profile_update, name = "profile-update"),
    
]

userauths/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    bio = models.CharField(max_length=200)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    image= models.ImageField(upload_to="image")
    full_name= models.CharField(max_length=200)
    bio = models.CharField(max_length=200,null=True,blank=True)
    phone = models.CharField(max_length=200)
    verified = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username 

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User,Profile

class UserRegisterForm(UserCreationForm):
    
        username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Username"}))
        email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder":"Email"}))
        password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password"}))
        password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Confirm Password"}))

        class Meta:
            model = User
            fields = ['username','email']

class ProfileForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Full Name"}))
    bio = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Bio"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"Phone"}))
    

    class Meta:
        model = Profile
        fields = ['full_name','image','bio','phone']

userauths/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from userauths.forms import UserRegisterForm , ProfileForm
from userauths.models import Profile


def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, Your account was created successfully")
            login(request, new_user)
            return redirect("core:index")
    else:
        form = UserRegisterForm()
    context = {'form': form}
    return render(request, "userauths/sign-up.html", context)

def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, "You are already logged in.")
        return redirect("core:index")

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        authenticated_user = authenticate(request, email=email, password=password)

        if authenticated_user is not None:
            login(request, authenticated_user)
            messages.success(request, "You are logged in.")
            return redirect("core:index")
        else:
            messages.warning(request, "User does not exist or incorrect password.")
            messages.warning(request, "Or create an account.")

    return render(request, "userauths/sign-in.html", {})

def logout_view(request):
    print("logout called")
    logout(request)
    messages.success(request, "You are logged out.")
    return redirect("userauths:sign-in")

def profile_update(request):
    profile = Profile.objects.get(user=request.user)
    if request.method =="POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect("core:dashboard")
    else:
        form= ProfileForm(instance=profile)        
   

    context ={
        "form":form,
        "profile":profile,
    }

    return render(request, "userauths/profile-edit.html",context)    

templates/userauths/profile-edit.html
{% extends 'partials/base.html' %} {% load static%} {%block content%}
<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> My Account
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 m-auto">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="dashboard-menu">
                                <ul class="nav flex-column" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="profile-tab" data-bs-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false"><i class="fi-rs-user">&nbsp;</i>Profile</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'userauths:sign-out' %}"><i class="fi-rs-sign-out mr-10"></i>Logout</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-md-9">
                            <div class="tab-content account dashboard-content pl-50">
                                <div class="tab-pane fade active show" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                    <div class="card">
                                        <div class="card-header border-bottom">
                                            <h3 class="mb-0">Update Profile</h3>
                                        </div>
                                        {% if form.errors %}
                                        <div class="alert-danger alert">
                                            <strong>{{form.errors}}</strong>
                                        </div>
                                        {% endif %}
                                        <div class="card-body mb-2" style="display: flex; align-items:center; gap:10px;">
                                            <div>
                                                {% if profile.image %}
                                                <span><img src="{{profile.image.url}}" style="width: 150px; object-fit:cover; height:150px; border-radius:50%;" alt=""></span>
                                                {% endif %}
                                            </div>
                                            &nbsp;&nbsp;&nbsp;&nbsp;
                                            <div>
                                                <form action="" method="POST" enctype="multipart/form-data">
                                                    {% csrf_token %}
                                                    <div class="mb-3">
                                                        {{form.full_name}}
                                                    </div>
    
                                                    <div class="mb-3">
                                                        {{form.bio}}
                                                    </div>
                                                    <div class="mb-3">
                                                        {{form.phone}}
                                                    </div>
                                                    <div class="mb-3">
                                                        {{form.image}}
                                                    </div>
                                                    
                                            
                                                    <button class="btn btn-success" type="submit">Save Changes</button>
                                                </form>
                                            </div>

                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{%endblock content%}

templates/userauths/sign-in.html
{% extends 'partials/base.html' %}

{% load static%}
{%block content%}
    <main class="main pages">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Pages <span></span> My Account
                </div>
            </div>
        </div>
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                        <div class="row">
                            <div class="col-lg-6 pr-30 d-none d-lg-block">
                                <img class="border-radius-15" src="{% static 'assets/imgs/page/login-1.jpg' %}" alt="" />
                            </div>
                            <div class="col-lg-6 col-md-8">
                                <div class="login_wrap widget-taber-content background-white">
                                    <div class="padding_eight_all bg-white">
                                        <div class="heading_s1">
                                            <h1 class="mb-5">Login</h1>
                                            <p class="mb-30">Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create here</a></p>
                                        </div>
                                        <form method="POST" >
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" required name="email" placeholder="Username or Email *" />
                                            </div>
                                            <div class="form-group">
                                                <input required type="password" name="password" placeholder="Your password *" />
                                            </div>
                                            <!-- <div class="login_footer form-group">
                                                <div class="chek-form">
                                                    <input type="text" required="" name="email" placeholder="Security code *" />
                                                </div>
                                                <span class="security-code">
                                                    <b class="text-new">8</b>
                                                    <b class="text-hot">6</b>
                                                    <b class="text-sale">7</b>
                                                    <b class="text-best">5</b>
                                                </span>
                                            </div> -->
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox1"><span>Remember me</span></label>
                                                    </div>
                                                </div>
                                                <a class="text-muted" href="#">Forgot password?</a>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-heading btn-block hover-up" name="login">Log in</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {%endblock content%}

templates/userauths/sign-up.html
{% extends 'partials/base.html' %}

{% load static%}
{%block content%}

<main class="main pages">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                <span></span> Pages <span></span> My Account
            </div>
        </div>
    </div>
    <div class="page-content pt-150 pb-150">
        <div class="container">
            <div class="row">
                <div class="col-xl-8 col-lg-10 col-md-12 m-auto">
                    <div class="row">
                        <div class="col-lg-6 col-md-8">
                            <div class="login_wrap widget-taber-content background-white">
                                <div class="padding_eight_all bg-white">
                                    {% if form.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ form.errors }}</strong>
                                    </div>
                                    {% endif %}

                                    <div class="heading_s1">
                                        <h1 class="mb-5">Create an Account</h1>
                                        <p class="mb-30">Already have an account? <a href="{% url 'userauths:sign-in' %}">Login</a>
                                        </p>
                                    </div>
                                    <form method="post" method="POST">
                                        {% csrf_token %}


                                        <div class="form-group">
                                            {{form.username}}
                                        </div>

                                        <div class="form-group">
                                            {{form.email}}
                                        </div>
                                        <div class="form-group">
                                            {{form.password1}}
                                        </div>
                                        <div class="form-group">
                                            {{form.password2}}
                                        </div>
                                        <!-- <div class="login_footer form-group">
                                                <div class="chek-form">
                                                    <input type="text" required="" name="email" placeholder="Security code *" />
                                                </div>
                                                <span class="security-code">
                                                    <b class="text-new">8</b>
                                                    <b class="text-hot">6</b>
                                                    <b class="text-sale">7</b>
                                                    <b class="text-best">5</b>
                                                </span>
                                            </div> -->
                                        <!-- <div class="payment_option mb-50">
                                                <div class="custome-radio">
                                                    <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="" />
                                                    <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">I am a customer</label>
                                                </div>
                                                <div class="custome-radio">
                                                    <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="" />
                                                    <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">I am an artist</label>
                                                </div>
                                            </div>
                                            <div class="login_footer form-group mb-50">
                                                <div class="chek-form">
                                                    <div class="custome-checkbox">
                                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox12" value="" />
                                                        <label class="form-check-label" for="exampleCheckbox12"><span>I agree to terms &amp; Policy.</span></label>
                                                    </div>
                                                </div>
                                                <a href="page-privacy-policy.html"><i class="fi-rs-book-alt mr-5 text-muted"></i>Lean more</a>
                                            </div> -->
                                        <div class="form-group mb-30">
                                            <button type="submit"
                                                class="btn btn-fill-out btn-block hover-up font-weight-bold"
                                                name="login">Submit &amp; Register</button>
                                        </div>
                                        <!-- <p class="font-xs text-muted"><strong>Note:</strong>Your personal data will be
                                            used to support your experience throughout this website, to manage access to
                                            your account, and for other purposes described in our privacy policy</p> -->
                                    </form>
                                </div>
                            </div>
                        </div>
                        <!-- <div class="col-lg-6 pr-30 d-none d-lg-block">
                            <div class="card-login mt-115">
                                <a href="#" class="social-login facebook-login">
                                    <img src="{% static 'assets/imgs/theme/icons/logo-facebook.svg' %}" alt="" />
                                    <span>Continue with Facebook</span>
                                </a>
                                <a href="#" class="social-login google-login">
                                    <img src="{% static 'assets/imgs/theme/icons/logo-google.svg' %}" alt="" />
                                    <span>Continue with Google</span>
                                </a>
                                
                                
                            </div>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{%endblock content%}